# Generated by Django 5.2.3 on 2025-06-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=255),
        ),
    ]
