# Generated by Django 5.2.3 on 2025-06-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_project_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_status',
            field=models.CharField(choices=[('processed', 'Processed'), ('pending', 'Pending'), ('failed', 'Failed'), ('draft', 'Draft')], default='draft', max_length=255),
        ),
    ]
