version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - media_files:/app/media
    ports:
      - "8000:8000"

  worker:
    build: ./backend
    restart: always
    command: celery -A project_root worker -l info -Q default
    env_file:
      - .env
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend:/app
      - media_files:/app/media

  frontend:
    build: ./frontend
    restart: always
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

  beat:
    build: ./backend
    command: celery -A project_root beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - backend
      - postgres
    volumes:
      - ./backend:/app
      - media_files:/app/media

  flower:
    image: mher/flower:1.2
    restart: always
    command: >
      celery --broker=${CELERY_BROKER_URL} --result-backend=${CELERY_RESULT_BACKEND} flower --port=${FLOWER_PORT}
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "5555:5555"

volumes:
  postgres_data:
  media_files:
  frontend_node_modules:
