version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: research_memory
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: project_root.settings
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/research_memory
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      DUCKDB_FILE: /data/analytics.duckdb
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - media_files:/app/media
    ports:
      - "8000:8000"

  worker:
    build: ./backend
    restart: always
    command: celery -A project_root worker -l info -Q default
    environment:
      DJANGO_SETTINGS_MODULE: project_root.settings
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/research_memory
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      DUCKDB_FILE: /data/analytics.duckdb
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend:/app
      - media_files:/app/media

  frontend:
    build: ./frontend
    restart: always
    environment:
      NODE_ENV: development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

  beat:
    build: ./backend
    command: celery -A project_root beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: project_root.settings
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend:/app
      - media_files:/app/media

volumes:
  postgres_data:
  media_files:
  frontend_node_modules:
